name: CI

on:
  push:
    branches:
      - main
      - dev
      - fix/ci

jobs:
  Unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}
      - name: Run unit tests
        run: chmod +x ./gradlew && ./gradlew test